<?xml version="1.0"?>
<!DOCTYPE TVSCHEDULE [
<!ELEMENT TVSCHEDULE (CHANNEL+)>
<!ELEMENT CHANNEL (BANNER,DAY+)>
<!ELEMENT BANNER (#PCDATA)>
<!ELEMENT DAY (DATE,(HOLIDAY|PROGRAMSLOT+)+)>
<!ELEMENT HOLIDAY (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT PROGRAMSLOT (TIME,TITLE,DESCRIPTION?)>
<!ELEMENT TIME (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ATTLIST TVSCHEDULE NAME CDATA #REQUIRED>
<!ATTLIST CHANNEL CHAN CDATA #REQUIRED>
<!ATTLIST PROGRAMSLOT VTR CDATA #IMPLIED>
<!ATTLIST TITLE RATING CDATA #IMPLIED>
<!ATTLIST TITLE LANGUAGE CDATA #IMPLIED>
]>
<TVSCHEDULE NAME="" >
    <CHANNEL CHAN="">
        <BANNER>JHI</BANNER>
        <DAY>
            <DATE></DATE>
            <HOLIDAY>HYH</HOLIDAY>
            
        </DAY>
    </CHANNEL>

    <CHANNEL CHAN="">
        <BANNER>JHI</BANNER>
        <DAY>
            <DATE></DATE>
            <PROGRAMSLOT>
                <TIME></TIME>
                <TITLE RATING= ""></TITLE>
                <DESCRIPTION></DESCRIPTION>
            </PROGRAMSLOT>
            
        </DAY>
    </CHANNEL>


</TVSCHEDULE>
